project_id = "armdnqyxszlwqvgjphnm"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.create-diarista-user]
verify_jwt = false

[functions.update-diarista-phone]
verify_jwt = false

[functions.smtp-send]
verify_jwt = false

[functions.smtp-config]
verify_jwt = false

[functions.password-reset-request]
verify_jwt = false

[functions.password-reset-confirm]
verify_jwt = false

[functions.notify-nota-fiscal]
verify_jwt = false

[functions.inter-pix-pagamento]
verify_jwt = false

[functions.pix-pagamento]
verify_jwt = false

[functions.criar-notificacao]
verify_jwt = false


