// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://armdnqyxszlwqvgjphnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFybWRucXl4c3psd3F2Z2pwaG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMjMzNjgsImV4cCI6MjA5MTc5OTM2OH0.e53VAMR1oMSwRY7Vv71AZ1o4JfY5aSRxBMAp3YQhRoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});